name: CI/CD - Fraud Detection

on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: backend
        run: |
          pip install -r requirements.txt

      - name: Train model
        working-directory: backend
        run: |
          python model/train.py

      - name: Run tests
        working-directory: backend
        run: |
          pytest tests/ -v


  deploy-backend:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/prod'

    steps:
      - name: Trigger Render deploy
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}